# -*- coding: utf-8 -*-
"""First_project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DIQxsD7SII3yt4qRwwBHKvhHZ5WEBCuY
"""

import numpy as np
import pandas as pd

! pip install requests

import requests

pip install tenacity

from tenacity import retry, wait_exponential, stop_after_attempt, retry_if_exception_type
import requests.exceptions

# importing the countries
url = "https://api.worldbank.org/countries?format=json&per_page=300"
response = requests.get(url)
response.status_code

response

data= response.json()
print(data) # mata data
print(len(data)) # 1 - mata data , 2 - actual data

countries = data[1]
countries = pd.DataFrame(countries)

countries.head(3)

countries['region'] = countries['region'].apply(lambda x: x['value'])

countries['incomeLevel'] = countries['incomeLevel'].apply(lambda x: x['value'])

countries['lendingType'] = countries['lendingType'].apply(lambda x: x['value'])

countries.drop(columns=['adminregion','capitalCity'],inplace=True)

countries.head(3)

countries['region'].unique()

countries.rename(columns={"iso2Code":"country_id"},inplace=True)

countries[countries['region']=='Aggregates'].head(3)

# Code for Indicators
base_url = 'https://api.worldbank.org/v2/indicators?format=json'
response = requests.get(base_url)
response.status_code

indicators_data = response.json()

indicators_data[0]

pd.DataFrame(indicators_data[1]).head(3)

all_dfs = []
for i in range(1,592):
  url = f'https://api.worldbank.org/v2/indicators?format=json&per_page=500&page={i}'
  response = requests.get(url)

  if response.status_code==200:
    data = response.json()

    if len(data)<2:
      print(f"No data at page{i}")

    indicators = data[1]
    df = pd.DataFrame({"id":item["id"],
                  "name":item["name"]} for item in indicators)
    all_dfs.append(df)
    print(f"Page{i}:{len(df)} indicators collected")

  else:
      print(f"Failed to fetch page{i}, status code:{response.status_code}")

final_df = pd.concat(all_dfs,ignore_index=True)

final_df.to_csv("final_df.csv")

# I need to extract values for various indicators under its domain for each country.

indicator_groups = {
    "economic_activity_growth": [
        "NY.GDP.MKTP.KD.ZG",  # GDP growth (annual %)
        "NY.GDP.PCAP.CD"      # GDP per capita (current US$)
    ],

    "labour_market_indicators": [
        "SL.UEM.TOTL.ZS",     # Unemployment total
        "SL.UEM.1524.ZS",     # Unemployment youth total (ages 15-24)
        "SL.TLF.TOTL.IN"      # Labour force, total
    ],

    "trade_globalization": [
        "NE.EXP.GNFS.CD",     # Exports of goods and services (current US$)
        "NE.IMP.GNFS.CD"      # Imports of goods and services (current US$)
    ],

    "poverty_inequality": [
        "SI.POV.NAHC",        # Poverty headcount ratio at national poverty lines (% of population)
        "SI.POV.GINI"         # Gini index (measure of income inequality)
    ],

    "environmental_indicators": [
        "EG.FEC.RNEW.ZS",     # Renewable energy consumption (% of total final energy consumption)
        "AG.LND.FRST.ZS"      # Forest area (% of land area)
    ],
    "health_indicators": [
    "SP.DYN.LE00.IN",       # Life expectancy at birth
    "SP.DYN.IMRT.IN",       # Infant mortality rate
    "SH.H2O.BASW.ZS",       # Access to at least basic water services (% of population)
    "SH.XPD.CHEX.GD.ZS",    # Current health expenditure (% of GDP)
    "SH.IMM.IDPT",          # Immunization, DPT (% of children ages 12-23 months)
    "SH.IMM.MEAS",          # Immunization, measles (% of children ages 12-23 months)
    "SH.MMR.RISK.ZS",       # Risk of maternal death
    "SH.DTH.COMM.ZS",       # Deaths from communicable diseases (% of total)
    "SH.TBS.INCD",          # Tuberculosis incidence (per 100,000 people)
    "SH.STA.BRTC.ZS",       # Births attended by skilled health staff (%)
    "SH.STA.MMRT",          # Maternal mortality ratio (modeled estimate, per 100,000 live births)
    "SP.POP.65UP.TO.ZS",    # Population ages 65 and above (% of total population)
    "SH.HIV.INCD.ZS"        # HIV incidence rate (per 1,000 uninfected population ages 15-49)
],
    "technology_indicators": [
    "IT.NET.USER.ZS",   # Individuals using the Internet (% of population)
    "IT.CEL.SETS.P2"    # Mobile cellular subscriptions (per 100 people)
]
}

import time
base_url = "https://api.worldbank.org/countries/all/indicators/{}?format=json&per_page=1000&page={}"

category_dataframes={}


for category, indicators in indicator_groups.items():
  print(f"Fatching information for category:{category}")
  all_dfs_for_category=[]

  for indicator_code in indicators:
    print(f"Fatching indicator:{indicator_code}")
    page = 1

    while True:
      url = base_url.format(indicator_code,page)
      response = requests.get(url)

      if response.status_code == 200:
        data = response.json()

        if len(data)<2:
          print(f"No data for indicator {indicator_code} at page {page} or unexpected data format.")
          break # No data or unexpected format, break from inner while loop

        total_pages = data[0]["pages"]
        record= data[1]
        df = pd.json_normalize(record)
        df = df[["country.id","country.value", "indicator.id","indicator.value","date","value"]].rename(columns=
         {"country.id":"country_id","country.value":"country_value",
          "indicator.id":"indicator_id","indicator.value":"indicator_name",
          "date":"year"})
        df= df[df["year"].astype(int)>2018]
        all_dfs_for_category.append(df)

        if page>=total_pages:
          break
        else:
          page+=1
          time.sleep(0.3)
      else:
        print(f"Failed to fetch data for indicator {indicator_code} at page {page}, status code: {response.status_code}")
        break # Break from inner while loop if request failed

  if all_dfs_for_category:
    combined_df = pd.concat(all_dfs_for_category,ignore_index=True)
    category_dataframes[category]=combined_df
    print(f"Total rows collected for category {category}: {len(combined_df)}")
  else:
    print(f"No data collected for category {category}")
print(f"Data Fatching Completed")

economic_activity = category_dataframes.get("economic_activity_growth", pd.DataFrame())
labour_market = category_dataframes.get("labour_market_indicators", pd.DataFrame())
trade_globalization = category_dataframes.get("trade_globalization", pd.DataFrame())
poverty_inequality = category_dataframes.get("poverty_inequality", pd.DataFrame())
environmental_indicators = category_dataframes.get("environmental_indicators", pd.DataFrame())
health_indicators = category_dataframes.get("health_indicators", pd.DataFrame())
technology_indicators = category_dataframes.get("technology_indicators", pd.DataFrame())

economic = pd.merge(economic_activity,countries,on="country_id",how="inner")
labour_market = pd.merge(labour_market,countries,on="country_id",how="inner")
trade = pd.merge(trade_globalization,countries,on="country_id",how="inner")
poverty = pd.merge(poverty_inequality,countries,on="country_id",how="inner")
environmental = pd.merge(environmental_indicators,countries,on="country_id",how="inner")
health = pd.merge(health_indicators,countries,on="country_id",how="inner")
technology = pd.merge(technology_indicators,countries,on="country_id",how="inner")

labour_market.drop(columns=["indicator_id","name","id"],inplace=True)
trade.drop(columns=["indicator_id","name","id"],inplace=True)
poverty.drop(columns=["indicator_id","name","id"],inplace=True)
environmental.drop(columns=["indicator_id","name","id"],inplace=True)
health.drop(columns=["indicator_id","name","id"],inplace=True)
technology.drop(columns=["indicator_id","name","id"],inplace=True)

economic.to_csv("economic.csv")
labour_market.to_csv("labour_market.csv")
trade.to_csv("trade.csv")
poverty.to_csv("poverty.csv")
environmental.to_csv("environmental.csv")
health.to_csv("health.csv")
technology.to_csv("technology.csv")


df_wide = health.pivot_table(index=['country_value','year'],
                             columns = 'indicator_name',
                             values = 'value')

corr = df_wide.corr()
import seaborn as sns
import matplotlib.pyplot as plt

plt.figure(figsize=(20,20), facecolor= 'none')
ax = sns.heatmap(
                  corr,
                  annot=True,
                  cmap='coolwarm',
                  cbar_kws={'label': 'Correlation'},
                  annot_kws = {"fontsize":14,"fontweight":"bold"}
)
plt.title('Realtionship between various Health indicators')
ax.tick_params(axis='x', labelsize=14)
ax.tick_params(axis='y', labelsize=14)
plt.show()

df_pivot = health.pivot_table(index=['country_value','year'],
                             columns = 'indicator_name',
                             values = 'value')

df_pivot.head(3)

plt.figure(figsize=(10,10), facecolor= 'none')
ax = sns.regplot(data = df_pivot,
                 x = "Current health expenditure (% of GDP)",
                 y = "Life expectancy at birth, total (years)",
                 scatter_kws= {"alpha":0.5, "s":40},
                 line_kws={"color":"red", "lw":2}
                 )
plt.title('Realtionship between Expenditure and Life Expectancy')
ax.set_xlabel("Current health expenditure (% of GDP)")
ax.set_ylabel("Life expectancy at birth")

